# Generated by Django 2.2.5 on 2019-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='path',
            field=models.CharField(blank=True, max_length=64, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='client',
            field=models.CharField(blank=True, max_length=64, verbose_name='client'),
        ),
    ]
