# Generated by Django 2.2.5 on 2019-09-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20190929_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
