# Generated by Django 2.2.6 on 2019-10-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20190929_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='path',
            field=models.FileField(upload_to='files'),
        ),
    ]
